pick_ball_mbot:
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  paddle_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: paddle_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}



