// Generated by gencpp from file pick_ball_mbot_msgs/PathPlanningResponse.msg
// DO NOT EDIT!


#ifndef PICK_BALL_MBOT_MSGS_MESSAGE_PATHPLANNINGRESPONSE_H
#define PICK_BALL_MBOT_MSGS_MESSAGE_PATHPLANNINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_ball_mbot_msgs
{
template <class ContainerAllocator>
struct PathPlanningResponse_
{
  typedef PathPlanningResponse_<ContainerAllocator> Type;

  PathPlanningResponse_()
    : Result(false)  {
    }
  PathPlanningResponse_(const ContainerAllocator& _alloc)
    : Result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Result_type;
  _Result_type Result;





  typedef boost::shared_ptr< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PathPlanningResponse_

typedef ::pick_ball_mbot_msgs::PathPlanningResponse_<std::allocator<void> > PathPlanningResponse;

typedef boost::shared_ptr< ::pick_ball_mbot_msgs::PathPlanningResponse > PathPlanningResponsePtr;
typedef boost::shared_ptr< ::pick_ball_mbot_msgs::PathPlanningResponse const> PathPlanningResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pick_ball_mbot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'pick_ball_mbot_msgs': ['/home/hyh/mc_ws/src/pick_ball_mbot/pick_ball_mbot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85ed39ee8c4e8f1c21743e6fe4dd523e";
  }

  static const char* value(const ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85ed39ee8c4e8f1cULL;
  static const uint64_t static_value2 = 0x21743e6fe4dd523eULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_ball_mbot_msgs/PathPlanningResponse";
  }

  static const char* value(const ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Result\n\
";
  }

  static const char* value(const ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathPlanningResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_ball_mbot_msgs::PathPlanningResponse_<ContainerAllocator>& v)
  {
    s << indent << "Result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_BALL_MBOT_MSGS_MESSAGE_PATHPLANNINGRESPONSE_H
