// Generated by gencpp from file pick_ball_mbot_msgs/PathPlanningRequest.msg
// DO NOT EDIT!


#ifndef PICK_BALL_MBOT_MSGS_MESSAGE_PATHPLANNINGREQUEST_H
#define PICK_BALL_MBOT_MSGS_MESSAGE_PATHPLANNINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_ball_mbot_msgs
{
template <class ContainerAllocator>
struct PathPlanningRequest_
{
  typedef PathPlanningRequest_<ContainerAllocator> Type;

  PathPlanningRequest_()
    : Request(false)  {
    }
  PathPlanningRequest_(const ContainerAllocator& _alloc)
    : Request(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Request_type;
  _Request_type Request;





  typedef boost::shared_ptr< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PathPlanningRequest_

typedef ::pick_ball_mbot_msgs::PathPlanningRequest_<std::allocator<void> > PathPlanningRequest;

typedef boost::shared_ptr< ::pick_ball_mbot_msgs::PathPlanningRequest > PathPlanningRequestPtr;
typedef boost::shared_ptr< ::pick_ball_mbot_msgs::PathPlanningRequest const> PathPlanningRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pick_ball_mbot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'pick_ball_mbot_msgs': ['/home/hyh/mc_ws/src/pick_ball_mbot/pick_ball_mbot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff201b53401f8d1221f1f88bb9daa999";
  }

  static const char* value(const ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff201b53401f8d12ULL;
  static const uint64_t static_value2 = 0x21f1f88bb9daa999ULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_ball_mbot_msgs/PathPlanningRequest";
  }

  static const char* value(const ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Request\n\
";
  }

  static const char* value(const ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathPlanningRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_ball_mbot_msgs::PathPlanningRequest_<ContainerAllocator>& v)
  {
    s << indent << "Request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_BALL_MBOT_MSGS_MESSAGE_PATHPLANNINGREQUEST_H
