// Generated by gencpp from file pick_ball_mbot_msgs/PathPlanning.msg
// DO NOT EDIT!


#ifndef PICK_BALL_MBOT_MSGS_MESSAGE_PATHPLANNING_H
#define PICK_BALL_MBOT_MSGS_MESSAGE_PATHPLANNING_H

#include <ros/service_traits.h>


#include <pick_ball_mbot_msgs/PathPlanningRequest.h>
#include <pick_ball_mbot_msgs/PathPlanningResponse.h>


namespace pick_ball_mbot_msgs
{

struct PathPlanning
{

typedef PathPlanningRequest Request;
typedef PathPlanningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathPlanning
} // namespace pick_ball_mbot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pick_ball_mbot_msgs::PathPlanning > {
  static const char* value()
  {
    return "2b99074ee17510311b29260db3a8ae84";
  }

  static const char* value(const ::pick_ball_mbot_msgs::PathPlanning&) { return value(); }
};

template<>
struct DataType< ::pick_ball_mbot_msgs::PathPlanning > {
  static const char* value()
  {
    return "pick_ball_mbot_msgs/PathPlanning";
  }

  static const char* value(const ::pick_ball_mbot_msgs::PathPlanning&) { return value(); }
};


// service_traits::MD5Sum< ::pick_ball_mbot_msgs::PathPlanningRequest> should match 
// service_traits::MD5Sum< ::pick_ball_mbot_msgs::PathPlanning > 
template<>
struct MD5Sum< ::pick_ball_mbot_msgs::PathPlanningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pick_ball_mbot_msgs::PathPlanning >::value();
  }
  static const char* value(const ::pick_ball_mbot_msgs::PathPlanningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_ball_mbot_msgs::PathPlanningRequest> should match 
// service_traits::DataType< ::pick_ball_mbot_msgs::PathPlanning > 
template<>
struct DataType< ::pick_ball_mbot_msgs::PathPlanningRequest>
{
  static const char* value()
  {
    return DataType< ::pick_ball_mbot_msgs::PathPlanning >::value();
  }
  static const char* value(const ::pick_ball_mbot_msgs::PathPlanningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pick_ball_mbot_msgs::PathPlanningResponse> should match 
// service_traits::MD5Sum< ::pick_ball_mbot_msgs::PathPlanning > 
template<>
struct MD5Sum< ::pick_ball_mbot_msgs::PathPlanningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pick_ball_mbot_msgs::PathPlanning >::value();
  }
  static const char* value(const ::pick_ball_mbot_msgs::PathPlanningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_ball_mbot_msgs::PathPlanningResponse> should match 
// service_traits::DataType< ::pick_ball_mbot_msgs::PathPlanning > 
template<>
struct DataType< ::pick_ball_mbot_msgs::PathPlanningResponse>
{
  static const char* value()
  {
    return DataType< ::pick_ball_mbot_msgs::PathPlanning >::value();
  }
  static const char* value(const ::pick_ball_mbot_msgs::PathPlanningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PICK_BALL_MBOT_MSGS_MESSAGE_PATHPLANNING_H
