// Generated by gencpp from file pick_ball_mbot_msgs/void_obstacle.msg
// DO NOT EDIT!


#ifndef PICK_BALL_MBOT_MSGS_MESSAGE_VOID_OBSTACLE_H
#define PICK_BALL_MBOT_MSGS_MESSAGE_VOID_OBSTACLE_H

#include <ros/service_traits.h>


#include <pick_ball_mbot_msgs/void_obstacleRequest.h>
#include <pick_ball_mbot_msgs/void_obstacleResponse.h>


namespace pick_ball_mbot_msgs
{

struct void_obstacle
{

typedef void_obstacleRequest Request;
typedef void_obstacleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct void_obstacle
} // namespace pick_ball_mbot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pick_ball_mbot_msgs::void_obstacle > {
  static const char* value()
  {
    return "94e2952797301ac06963adb1824707fa";
  }

  static const char* value(const ::pick_ball_mbot_msgs::void_obstacle&) { return value(); }
};

template<>
struct DataType< ::pick_ball_mbot_msgs::void_obstacle > {
  static const char* value()
  {
    return "pick_ball_mbot_msgs/void_obstacle";
  }

  static const char* value(const ::pick_ball_mbot_msgs::void_obstacle&) { return value(); }
};


// service_traits::MD5Sum< ::pick_ball_mbot_msgs::void_obstacleRequest> should match 
// service_traits::MD5Sum< ::pick_ball_mbot_msgs::void_obstacle > 
template<>
struct MD5Sum< ::pick_ball_mbot_msgs::void_obstacleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pick_ball_mbot_msgs::void_obstacle >::value();
  }
  static const char* value(const ::pick_ball_mbot_msgs::void_obstacleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_ball_mbot_msgs::void_obstacleRequest> should match 
// service_traits::DataType< ::pick_ball_mbot_msgs::void_obstacle > 
template<>
struct DataType< ::pick_ball_mbot_msgs::void_obstacleRequest>
{
  static const char* value()
  {
    return DataType< ::pick_ball_mbot_msgs::void_obstacle >::value();
  }
  static const char* value(const ::pick_ball_mbot_msgs::void_obstacleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pick_ball_mbot_msgs::void_obstacleResponse> should match 
// service_traits::MD5Sum< ::pick_ball_mbot_msgs::void_obstacle > 
template<>
struct MD5Sum< ::pick_ball_mbot_msgs::void_obstacleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pick_ball_mbot_msgs::void_obstacle >::value();
  }
  static const char* value(const ::pick_ball_mbot_msgs::void_obstacleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pick_ball_mbot_msgs::void_obstacleResponse> should match 
// service_traits::DataType< ::pick_ball_mbot_msgs::void_obstacle > 
template<>
struct DataType< ::pick_ball_mbot_msgs::void_obstacleResponse>
{
  static const char* value()
  {
    return DataType< ::pick_ball_mbot_msgs::void_obstacle >::value();
  }
  static const char* value(const ::pick_ball_mbot_msgs::void_obstacleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PICK_BALL_MBOT_MSGS_MESSAGE_VOID_OBSTACLE_H
